version: "3.5"

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=admin123
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb --bind "redis"
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - default

volumes:
  redis-data:
  mongodb-data:

networks:
  default:
    name: network
